export const quickLaunchCities = [
  "London",
  "Berlin",
  "New York City",
  "Paris",
  "Munich",
  "Amsterdam",
  "Rome",
  "Barcelona",
  "Madrid",
  "Prague",
  "Vienna",
  "Budapest",
  "Dublin",
  "Lisbon",
  "Brussels",
  "Copenhagen",
  "Stockholm",
  "Athens",
  "Helsinki",
  "Oslo",
  "Warsaw",
  "Zurich",
  "Moscow",
  "Istanbul",
  "Saint Petersburg",
  "Bucharest",
  "Edinburgh",
  "Venice",
  "Florence",
  "Milan",
  "Naples",
  "Luxembourg City",
  "Reykjavik",
  "Monaco",
  "Vatican City",
];

export const unknownClerkUser = {
  id: "user_2YxVp66u0zvMgoN7zOSm6sJiiHb",
};

export const unknownItinerary = {
  id: "fake",
};
